### ISSUE TITLE
交易hash怎么计算？

### ISSUE THREAD

**Issue by anysoft** [orientwalt/apidoc_2020#4]
交易签名前新版本使用的sha256对json的字节数组进行hash

交易签名后怎么计算hash？我需要在不广播的前提下计算出签名后的hash。

7b2274797065223a22617574682f5374645478222c2276616c7565223a7b226d7367223a5b7b2274797065223a2268746466736572766963652f73656e64222c2276616c7565223a7b2246726f6d223a2268746466317267736678617630616638613739636d747136726e6a746a6b716e676c3971636a386b396c37222c22546f223a226874646631737265707768747372723334667937747933667379686b646776796867646172767568736567222c22416d6f756e74223a5b7b2264656e6f6d223a227361746f736869222c22616d6f756e74223a22313030227d5d2c2244617461223a22222c224761735072696365223a22313030222c2247617357616e746564223a22323030303030227d7d5d2c22666565223a7b226761735f77616e746564223a22323030303030222c226761735f7072696365223a22313030227d2c227369676e617475726573223a5b7b227075625f6b6579223a7b2274797065223a2274656e6465726d696e742f5075624b6579536563703235366b31222c2276616c7565223a22412f75616e615a68303934772b5071756d54574d5a6a6a6641796c744a7a497350356e3134376768752b3446227d2c227369676e6174757265223a226479465572714551395676763370586c577936595a422b422f666e65673469687a6a4e372f475238466d787567674b334c576d497a674f4a436c6549756952676337465454475948696b796b4a69494a734741376b513d3d227d5d2c226d656d6f223a22227d7d

hash为：
2041AD03C1FAC73DC4C7214995E0FA7FA25981601E2085A4BA564463A7742048

**Comment by gaojunying** [comment]
tx hash is results of sha256 of tx byte. you will understand when you watch the corresponding part of tendermint source code.

https://github.com/tendermint/tendermint/blob/master/types/tx.go#L22
```go
func (tx Tx) Hash() []byte {
	return tmhash.Sum(tx)
}
```
https://github.com/tendermint/tendermint/blob/master/crypto/tmhash/hash.go#L19
```go
func Sum(bz []byte) []byte {
	h := sha256.Sum256(bz)
	return h[:]
}
```
